-- Initial team library distilled from existing custom budgets. These are
-- reusable allowance structures, not proposal scope; staff still reviews them.
INSERT INTO public.section_library (id, name, description, category, tags, payload, created_by)
VALUES
('seed-equipment-rack', 'Equipment Rack, Surge, & Battery Backup', 'Use when a one-off project needs an explicit equipment-rack and power-protection allowance.', 'Infrastructure', ARRAY['rack','power','surge','battery'], $json${"name":"Equipment Rack, Surge, & Battery Backup","icon":"🔋","section":"Infrastructure","required":false,"presentationMode":"list","tiers":{"good":{"enabled":true,"label":"Basic Rack","price":1000,"features":[]},"standard":{"enabled":true,"label":"Surge Protection","price":1800,"features":["Equipment surge protection"]},"better":{"enabled":true,"label":"Surge & Battery Backup","price":3500,"features":["Equipment surge protection","Battery backup"]}}}$json$::jsonb, 'seed'),
('seed-driveway-surveillance', 'Driveway Surveillance', 'Use for long-driveway or detached-entry camera coverage. Confirm pathways, camera count, and distances.', 'Security', ARRAY['security','cameras','driveway','outdoor'], $json${"name":"Driveway Surveillance","icon":"📹","section":"Security","required":false,"presentationMode":"list","tiers":{"good":{"enabled":true,"label":"Standard Coverage","price":5400,"features":["Driveway coverage","Weather-rated night vision","Vehicle detection"]},"better":{"enabled":true,"label":"360° Coverage","price":7500,"features":["Driveway coverage","Weather-rated night vision","360° coverage"]},"best":{"enabled":true,"label":"360° + License Plate Reader","price":9500,"features":["360° coverage","Dedicated license plate reader"]}}}$json$::jsonb, 'seed'),
('seed-house-surveillance', 'House Surveillance', 'Use for a separate residential surveillance allowance when the standard camera category does not fit the project.', 'Security', ARRAY['security','cameras','home','perimeter'], $json${"name":"House Surveillance","icon":"🏡","section":"Security","required":false,"presentationMode":"list","tiers":{"good":{"enabled":true,"label":"Key Coverage","price":3600,"features":["Primary approach coverage","Primary activity-area coverage"]},"better":{"enabled":true,"label":"Enhanced Coverage","price":4200,"features":["Additional exterior angle"]},"best":{"enabled":true,"label":"Ideal Coverage","price":7200,"features":["Full perimeter coverage"]}}}$json$::jsonb, 'seed'),
('seed-gate-surveillance', 'Gate Surveillance', 'Use for a dedicated gate-camera allowance. Confirm pole, power, network path, and viewing distance.', 'Security', ARRAY['security','gate','camera','entry'], $json${"name":"Gate Surveillance","icon":"🚧","section":"Security","required":false,"presentationMode":"list","tiers":{"standard":{"enabled":true,"label":"Key Coverage","price":1200,"features":["4K wide-angle view"]},"best":{"enabled":true,"label":"High-Performance Coverage","price":1800,"features":["High-performance low-light camera","Adjustable viewing angle","Extended night vision"]}}}$json$::jsonb, 'seed'),
('seed-barn-surveillance', 'Barn Surveillance', 'Use for detached barn or equestrian-building coverage. Verify stall count, exterior coverage, and recording requirements.', 'Security', ARRAY['security','barn','equestrian','cameras'], $json${"name":"Barn Surveillance","icon":"🐎","section":"Security","required":false,"presentationMode":"list","tiers":{"standard":{"enabled":true,"label":"Key Coverage","price":13800,"features":["Interior coverage","Stall coverage","14+ day recording"]},"better":{"enabled":true,"label":"Enhanced Coverage","price":18400,"features":["360° main-interior coverage","Enhanced outdoor coverage","21+ day recording"]},"best":{"enabled":true,"label":"Ideal Coverage","price":26900,"features":["Maximum interior and exterior coverage","30+ day recording"]}}}$json$::jsonb, 'seed'),
('seed-access-control', 'Access Control', 'Use for multi-door managed entry systems. Pricing is based on a six-entry example and must be adjusted to door count.', 'Security', ARRAY['security','doors','access-control','commercial'], $json${"name":"Access Control","icon":"🚪","section":"Security","required":false,"presentationMode":"list","tiers":{"standard":{"enabled":true,"label":"Managed Entry","price":31500,"features":["Multiple entry methods","PIN, keyfob, wallet, and NFC access","Expandable platform"]},"best":{"enabled":true,"label":"Managed Entry + Video Readers","price":34500,"features":["Face recognition access","Built-in recording","Two-way communication"]}}}$json$::jsonb, 'seed'),
('seed-shades-prewire', 'Shades Pre-wire', 'Use during construction to compare pre-wire coverage areas. Replace room groupings with the project-specific plan.', 'Lighting & Shades', ARRAY['shades','prewire','construction','lighting'], $json${"name":"Shades Pre-wire","icon":"🪟","section":"Lighting & Shades","required":false,"presentationMode":"list","tiers":{"standard":{"enabled":true,"label":"Common Areas","price":5500,"features":["Primary common-area shade locations"]},"better":{"enabled":true,"label":"Add Primary Suite","price":8000,"features":["Common areas","Primary suite"]},"best":{"enabled":true,"label":"Full Home","price":11500,"features":["Whole-home shade pre-wire allowance"]}}}$json$::jsonb, 'seed'),
('seed-85-display', '85-inch Display', 'Use for a single large-format commercial or specialty display allowance.', 'Video', ARRAY['video','display','85-inch','commercial'], $json${"name":"85-inch Display","icon":"📺","section":"Video","required":false,"presentationMode":"list","tiers":{"good":{"enabled":true,"label":"Good","price":5200,"features":["4K UHD","Commercial installation use","Anti-glare coating"]},"better":{"enabled":true,"label":"Better","price":6200,"features":["Higher brightness","4K UHD","Anti-glare coating"]},"best":{"enabled":true,"label":"Best","price":7500,"features":["Peak brightness","Deep-black non-glare treatment"]}}}$json$::jsonb, 'seed'),
('seed-mezzanine-tv', 'Mezzanine TV', 'Use for a secondary-room 65-inch display comparison; confirm current models and pricing.', 'Video', ARRAY['video','tv','65-inch','secondary-room'], $json${"name":"Mezzanine TV","icon":"🖥️","section":"Video","required":false,"presentationMode":"list","tiers":{"good":{"enabled":true,"label":"65-inch Standard","price":1500,"features":[]},"better":{"enabled":true,"label":"65-inch Premium","price":2600,"features":["Wide viewing angle","Extended replacement warranty"]},"best":{"enabled":true,"label":"65-inch Flagship","price":3600,"features":["Enhanced brightness and reflection handling"]}}}$json$::jsonb, 'seed'),
('seed-upstairs-tv', 'Upstairs TV', 'Use for a large secondary-room display comparison; confirm room size, viewing distance, and current models.', 'Video', ARRAY['video','tv','large-format','secondary-room'], $json${"name":"Upstairs TV","icon":"🖥️","section":"Video","required":false,"presentationMode":"list","tiers":{"good":{"enabled":true,"label":"75-inch Premium","price":3350,"features":[]},"standard":{"enabled":true,"label":"85-inch Premium","price":4300,"features":["Wide viewing angle"]},"better":{"enabled":true,"label":"85-inch Flagship","price":6850,"features":["Enhanced brightness and reflection handling"]},"best":{"enabled":true,"label":"98-inch Premium","price":9400,"features":["Large-format premium display"]}}}$json$::jsonb, 'seed')
ON CONFLICT DO NOTHING;
